package parser;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * Standardizes .gateway and .keyring files (auto-generated by ceph)
 * 
 * @author PKelaita
 * @version 1.0
 *
 */
public class ParseCephData extends AbstractParser {

	/**
	 * Standardizes input File into a Map of keys and values.
	 * 
	 * @param input
	 *            the File to be standardized
	 */
	public void standardize(File input) {
		String name = input.getAbsolutePath();

		try {
			FileReader fr = new FileReader(input);
			BufferedReader br = new BufferedReader(fr);

			String line;
			while ((line = br.readLine()) != null) {
				if (line.length() == 0 || line.charAt(0) == '#') {
					continue;
				}

				if (line.charAt(0) == '[' && line.charAt(line.length() - 1) == ']') {
					String header = line.substring(1, line.length() - 1);
					data.put("Header", header);
					continue;
				} else if (line.endsWith("==")) {
					line = line.substring(0, line.length() - 2);
				}

				String[] arr = line.split("=");
				String key = arr[0].replace("\t", "");
				String val = arr[1];

				data.put(key, val);

			}

			br.close();
		} catch (IOException e) {
			System.err.println("\n[DATABASE ERROR] " + name + " is not in correct .keyring/.gateway format.\n");
			error = true;
		}
	}
}
