package parser;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * Standardizes .gateway and .keyring files (auto-generated by ceph)
 * 
 * @author PKelaita
 * @version 1.0
 *
 */
public class ParseCephData extends AbstractParser {

	/**
	 * Standardizes input File into a Map of keys and values.
	 * 
	 * @param input
	 *            the File to be standardized
	 */
	public void standardize(File input) {
		String name = input.getAbsolutePath();

		try {
			FileReader fr = new FileReader(input);
			BufferedReader br = new BufferedReader(fr);

			String line;
			String header = null;
			while ((line = br.readLine()) != null) {
				if (line.length() == 0 || line.charAt(0) == '#') {
					continue;
				}
				
				if (line.charAt(0) == '[' && line.charAt(line.length() - 1) == ']') {
					header = line.substring(1, line.length() - 1) + ".";
					continue;
				}

				String key = header + line.substring(1, line.indexOf('='));
				String val = line.substring(line.indexOf('=') + 1, line.length());
				data.put(key, val);

			}

			br.close();
		} catch (IOException e) {
			System.err.println("\n[DATABASE ERROR] " + name + " is not in correct .keyring/.gateway format.\n");
			error = true;
		}
	}
}
