#!/usr/bin/expect -f

set timeout 1
set pass

spawn sh -c "mkdir target"

set baseIP 10.0.113.
for {set VMIP 33} {$VMIP <= 43} {incr VMIP} {
	spawn sh -c "ssh sysops@$baseIP$VMIP bash < jar-generator.sh"
	expect "assword:"
	send "$pass\r"
	expect eof
	spawn sh -c "sftp sysops@$baseIP$VMIP"
	expect "assword:"
	send "$pass\r"
	expect "$"
	send "get *.jars\r"
	expect "$"
	send "rm *.jars\r"
	expect "$"
	send "exit\r"
	spawn sh -c "mv *.jars target/"
	interact
}
